--- 
abstract: Easy configuration base class for your App.
author: John Cappiello <jcap@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: App-Config
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cwd: 0
  File::Basename: 0
  File::HomeDir: 0.6
  File::Spec: 0
  Sub::Exporter: 0.972
  YAML::Syck: 0
version: 0.001
